### ISSUE TITLE
Add examples of how to add channel priorities to environment files.

### ISSUE THREAD

**Issue by davidrpugh** [carpentries-incubator/introduction-to-conda-for-data-scientists#44]
Need explicit discussion of how to add channel priorities to environment files. Typical way is to add a `channels` section to your `environment.yml` file.

```yaml
name: null

channels:
  - conda-forge
  - defaults

...
```

Priority is from highest to lowest, so in the above the `conda-forge` channel would be given highest priority.
